export enum RoleList {
    ALL = "ALL",
    ADMIN = "ADMIN",
    ALL_INFO_USERS = "ALL-INFO-USERS",
    PUBLICATIONS = "USERS-PUBLICATIONS",
    VERIFIED = "VERIFIED",
    USER = "USER",
    USER_CONTROL = "USER-CONTROL",
    USER_ROLE = "USER-ROLE",
    USER_POSITION = "USER-POSITION",
    USER_COMMENT = "USER-COMMENT"
}